import type { NextPage } from "next";
import React, { FC } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Grid from "@mui/material/Grid";
import Avatar from "@mui/material/Avatar";
import Button from "@mui/material/Button";

import TopNavigationBar from "../../components/TopNavigationBar";
//0x991d4BF206Ec205CC23BB1A851D0bF3F068b20A6
type TierProps = { title: string; description: string; price: number };

type UserProps = {
  coverPhoto: string;
  accountTitle: string;
  accountDescription: string;
  tiers: TierProps[];
};

const userData: UserProps = {
  coverPhoto:
    "https://images.unsplash.com/photo-1502759683299-cdcd6974244f?auto=format&fit=crop&w=440&h=220&q=60",
  accountTitle: "Ryan's Account",
  accountDescription:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nulla nibh, semper ut erat sed, hendrerit accumsan turpis. Nullam sollicitudin vulputate ante ac tincidunt.",
  tiers: [
    { title: "entry", description: "entry one", price: 1 },
    { title: "inter", description: "tiner one", price: 3 },
  ],
};

const Tiers: FC<TierProps> = ({ title, description, price }) => {
  return (
    <div>
      <h6>{title}</h6>
      <p>{description}</p>
      <p>{price}</p>
    </div>
  );
};

const Home: NextPage = () => {
  const TierPricing = userData.tiers.map((el: TierProps) => (
    <Tiers
      key={el.title}
      title={el.title}
      description={el.description}
      price={el.price}
    />
  ));
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavigationBar />
      <div
        style={{
          backgroundImage: `url("${userData.coverPhoto}")`,
          height: "350px",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
        }}
      />
      <Grid sx={{ mt: 2 }} container spacing={2}>
        <Grid xs={4} item>
          <div style={{ display: "flex", justifyContent: "flex-end" }}>
            <div
              style={{
                width: "60%",
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
              }}
            >
              <Avatar />
              <h4>{userData.accountTitle}</h4>
              <p style={{ textAlign: "center" }}>
                {userData.accountDescription}
              </p>
            </div>
          </div>
        </Grid>
        <Grid xs={4} item>
          <div
            style={{
              border: "1px solid #dbdbdb",
              borderRadius: "4px",
              padding: "10px",
            }}
          ></div>
        </Grid>
        <Grid xs={4} item>
          <div style={{ width: "60%" }}>
            <div
              style={{
                border: "1px solid #dbdbdb",
                borderRadius: "4px",
                padding: "10px",
              }}
            >
              {TierPricing}
            </div>
          </div>
        </Grid>
      </Grid>
    </div>
  );
};

export default Home;
