import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import AccountCreation from "../components/AccountCreation";
import LoggedOutScreen from "../components/LoggedOutScreen";
import TopNavigationBar from "../components/TopNavigationBar";
import Grid from "@mui/material/Grid";
import { users } from "../types/users";
import Avatar from "@mui/material/Avatar";
import Paper from "@mui/material/Paper";

type HomeProps = {
  walletKey: string | null;
  setWalletKey: (state: string | null) => void;
  account: users | null;
};
const Home: NextPage<HomeProps> = ({ walletKey, setWalletKey, account }) => {
  if (!walletKey) {
    return (
      <LoggedOutScreen walletKey={walletKey} setWalletKey={setWalletKey} />
    );
  }
  if (!account) return <AccountCreation walletKey={walletKey} />;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopNavigationBar
          walletKey={walletKey}
          account={account}
          setWalletKey={setWalletKey}
        />
        <div style={{ marginTop: "60px", padding: "20px" }}>
          <Grid container spacing={2}>
            <Grid item xs={3}>
              <Paper
                sx={{
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  p: 2,
                }}
              >
                <Avatar src={account.profile_picture} alt="profile pictore" />
                <p>{account.title}</p>
                <p>{`${account.first_name} ${account.last_name}`}</p>
              </Paper>
            </Grid>
            <Grid item xs={6}>
              hi
            </Grid>
            <Grid item xs={3}>
              hi
            </Grid>
          </Grid>
        </div>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
