import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import AccountCreation from "../components/AccountCreation";
import LoggedOutScreen from "../components/LoggedOutScreen";
import TopNavigationBar from "../components/TopNavigationBar";
import { users } from "../types/users";

type HomeProps = {
  walletKey: string | null;
  setWalletKey: (state: string | null) => void;
  account: users | null;
};
const Home: NextPage<HomeProps> = ({ walletKey, setWalletKey, account }) => {
  if (!walletKey) {
    return (
      <LoggedOutScreen walletKey={walletKey} setWalletKey={setWalletKey} />
    );
  }
  if (!account) return <AccountCreation walletKey={walletKey} />;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopNavigationBar
          walletKey={walletKey}
          account={account}
          setWalletKey={setWalletKey}
        />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
